architecture_search_multiprocessing: 1
fixed_architecture: true
fixed_spatial_unrolling: false
fixed_temporal_mapping: false
im2col_enable_for_all_layers: false
im2col_enable_for_pointwise_layers: true
layer_filename: ./NN_layers/AlexNet
layer_indices: [1, 2, 3]
layer_multiprocessing: 1
max_nb_lpf_layer: 7
result_filename: AlexNet
result_path: ./results_test
result_print_mode: complete
result_print_type: xml
save_all_architecture_result: true
save_all_spatial_unrolling_result: true
save_all_temporal_mapping_result: false
save_results_on_the_fly: true
spatial_unrolling_multiprocessing: 1
spatial_unrolling_search_method: hint_driven
spatial_utilization_threshold: 0.9
temporal_mapping_multiprocessing: 8
temporal_mapping_search_method: loma
